-- local null_ls = require("null-ls")
--
-- null_ls.setup({
--     sources = {
--         null_ls.builtins.formatting.stylua,
--         null_ls.builtins.diagnostics.eslint,
--         null_ls.builtins.completion.spell,
--         null_ls.builtins.code_actions.cspell,
--         null_ls.builtins.code_actions.eslint,
--         null_ls.builtins.code_actions.refactoring,
--         null_ls.builtins.diagnostics.cspell,
--         null_ls.builtins.diagnostics.eslint,
--         null_ls.builtins.diagnostics.fish,
--         null_ls.builtins.diagnostics.flake8,
--         null_ls.builtins.diagnostics.markdownlint,
--         null_ls.builtins.formatting.black,
--         null_ls.builtins.formatting.fish_indent,
--         null_ls.builtins.formatting.mdformat,
--         null_ls.builtins.formatting.prettier,
--         null_ls.builtins.formatting.shfmt,
--         null_ls.builtins.formatting.stylua,
--         null_ls.builtins.code_actions.gitsigns,
--     },
-- })
