#!/bin/sh

# Use neovim for vim if present.
[ -x "$(command -v nvim)" ] && alias vim="nvim" vimdiff="nvim -d" vi="nvim"

# Use $XINITRC variable if file exists.
[ -f "$XINITRC" ] && alias startx="startx $XINITRC"

# sudo not required for some system commands
for command in mount umount sv pacman updatedb su shutdown poweroff reboot ; do
	alias $command="sudo $command"
done; unset command

se() { cd ~/.local/bin; $EDITOR $(fzf) ;}

# Verbosity and settings that you pretty much just always are going to want.
alias \
	cp="cp -iv" \
	mv="mv -iv" \
	rm="rm -vI" \
	bc="bc -ql" \
	mkd="mkdir -pv" \
	yt="yt-dlp --embed-metadata -i" \
	yta="yt -x -f bestaudio/best" \
	ffmpeg="ffmpeg -hide_banner"

# Colorize commands when possible.
alias \
	grep="grep --color=auto" \
	diff="diff --color=auto" \
	ccat="highlight --out-format=ansi" \
	ip="ip -color=auto" \


# These common commands are just too long! Abbreviate them.
alias \
	ka="killall" \
	g="git" \
	trem="transmission-remote" \
	YT="youtube-viewer" \
	sdn="shutdown -h now" \
	e="$EDITOR" \
	v="$EDITOR" \
	p="pacman" \
	xi="sudo xbps-install" \
	xr="sudo xbps-remove -R" \
	xq="xbps-query" \
	z="zathura"

alias \
	lf="lfub" \
	magit="nvim -c MagitOnly" \
	ref="shortcuts >/dev/null; source ${XDG_CONFIG_HOME:-$HOME/.config}/shell/shortcutrc ; source ${XDG_CONFIG_HOME:-$HOME/.config}/shell/zshnameddirrc" \
	weath="less -S ${XDG_CACHE_HOME:-$HOME/.cache}/weatherreport" \
    du="du -h -c" \
    df="df -h" \
    http="xh" \
    lpath='echo $PATH | tr ":" "\n"' \
    nr="npm run" \
    docker="nerdctl" \
    reload!='RELOAD=1 source ~/.config/zsh/.zshrc'

# Better ls
alias \
    ls="exa --color=always" \
    l="exa -lah" \
    ll="exa -lFh" \
    lld="exa -l | grep ^d"

# Better tmux
alias \
    ta='tmux attach' \
    tls='tmux ls' \
    tat='tmux attach -t' \
    tns='tmux new-session -s'

# Better kubectl
alias \
    k="kubectl" \
    ka="kubectl access-matrix" \
    kap="kubectl access-matrix for pods" \
    kev="kubectl delete pods -A --field-selector=status.phase=Failed"

# Better cat
alias \
    cat="bat" \
    c="bat"
